/**
 * Quiz System - Type Definitions
 *
 * Types for the interactive quiz system that tests student knowledge.
 */

// ============================================================================
// QUIZ TYPES
// ============================================================================

/**
 * Type of quiz question
 */
export type QuizQuestionType = 'multiple-choice' | 'true-false' | 'code-completion'

/**
 * A complete quiz with multiple questions
 */
export interface Quiz {
  id: string                              // Unique ID: 'html-quiz-1'
  lessonId: string                        // Associated lesson: 'lesson-1'
  title: string                           // Quiz title
  description?: string                    // Optional description
  questions: QuizQuestion[]               // Array of questions
  passingScore?: number                   // Minimum score to pass (default: 70%)
  timeLimit?: number                      // Optional time limit in minutes
}

/**
 * A single quiz question
 */
export interface QuizQuestion {
  id: string                              // Unique ID within quiz: 'q1'
  question: string                        // The question text
  type: QuizQuestionType                  // Type of question
  options?: string[]                      // Options for multiple-choice (required for multiple-choice)
  correctAnswer: string | number          // Correct answer (index for multiple-choice, 'true'/'false' for true-false, string for code)
  explanation: string                     // Explanation of the correct answer
  points: number                          // Points for this question (default: 1)
  difficulty?: 'easy' | 'medium' | 'hard' // Optional difficulty
  hint?: string                           // Optional hint
}

/**
 * Student's answer to a quiz question
 */
export interface QuizAnswer {
  questionId: string                      // Question being answered
  answer: string | number                 // Student's answer
  correct: boolean                        // Whether the answer was correct
  pointsEarned?: number                   // Points earned for this question
  timeSpent?: number                      // Optional time spent on this question (seconds)
  hintsUsed?: boolean                     // Whether hints were used
}

/**
 * A quiz attempt by a student
 */
export interface QuizAttempt {
  id?: string                             // Database ID (optional, generated by DB)
  quizId: string                          // Quiz being attempted
  lessonId: string                        // Associated lesson
  studentId: string                       // Student UUID
  answers: QuizAnswer[]                   // All answers
  score: number                           // Points obtained
  maxScore: number                        // Maximum possible points
  percentage: number                      // Score percentage (0-100)
  passed: boolean                         // Whether student passed
  xpEarned: number                        // XP earned from this attempt
  completedAt: Date                       // Completion timestamp
  timeSpent?: number                      // Total time spent (seconds)
}

/**
 * Quiz result summary
 */
export interface QuizResult {
  attempt: QuizAttempt                    // The attempt data
  feedback: QuizFeedback[]                // Feedback for each question
  recommendations?: string[]              // Recommendations for improvement
}

/**
 * Feedback for a quiz question
 */
export interface QuizFeedback {
  questionId: string                      // Question ID
  correct: boolean                        // Whether answer was correct
  userAnswer: string | number             // What the student answered
  correctAnswer: string | number          // The correct answer
  explanation: string                     // Explanation
  message: string                         // Friendly feedback message
}

// ============================================================================
// QUIZ STATISTICS
// ============================================================================

/**
 * Statistics for a specific quiz
 */
export interface QuizStatistics {
  quizId: string                          // Quiz ID
  totalAttempts: number                   // Total attempts by all students
  averageScore: number                    // Average score (0-100)
  passRate: number                        // Percentage of students who passed
  averageTime: number                     // Average time spent (seconds)
  questionStats: QuestionStatistics[]     // Stats for each question
}

/**
 * Statistics for a specific question
 */
export interface QuestionStatistics {
  questionId: string                      // Question ID
  correctRate: number                     // Percentage of correct answers
  averageTime: number                     // Average time spent (seconds)
  commonWrongAnswers: Array<{             // Most common wrong answers
    answer: string | number
    count: number
  }>
}
